uniconhq/backend

- .env.example
- .gitignore
- unicon_backend/data/test_answer.json
- unicon_backend/data/test_submission.json
- unicon_backend/evaluator.py
- unicon_backend/evaluator/answer.py
- unicon_backend/evaluator/project.py
- unicon_backend/evaluator/tasks/programming.py
- unicon_backend/helpers/constants.py
- unicon_backend/templates/__init__.py
- unicon_backend/templates/run.jinja
`uv run ./unicon_backend/evaluator.py unicon_backend/data/test_submission.json unicon_backend/data/test_answer.json`
> feat: generate python file from answer

- unicon_backend/evaluator/tasks/programming.py
change to polling to match https://github.com/uniconhq/unicon-runner/pull/1/commits/026d34c00e1ceb9d9ad076f0fc7fa048fc37593c
> feat: switch to polling + evaluate programming task answer

- unicon_backend/app.py
- unicon_backend/constants.py
- unicon_backend/database.py
- unicon_backend/dependencies.py
- unicon_backend/routers/auth.py
Minor refactor to use `sqlalchemy.orm.sessionmaker` for session creations
> refactor: db session management

- unicon_backend/app.py
- unicon_backend/evaluator.py
- unicon_backend/evaluator/tasks/__init__.py
- unicon_backend/evaluator/tasks/base.py
- unicon_backend/evaluator/tasks/programming.py
- unicon_backend/logger.py
- unicon_backend/models/contest.py
- unicon_backend/workers.py
> feat: task publisher connection reuse

- unicon_backend/evaluator/contest.py
- unicon_backend/evaluator/tasks/programming/steps.py
- unicon_backend/evaluator/tasks/programming/task.py
- unicon_backend/lib/common.py
- unicon_backend/lib/graph.py
This PR implements a new `LoopStep` node. To achieve this, I had to introduce the idea of "control edges" and decouple dependencies between steps/nodes from solely data dependencies, which is implicit in our existing implementation. 
With control edges, we are also able to express the semantics of subgraphs on the top level without any nesting. This is inspired by how [Unity Visual Scripting](https://docs.unity3d.com/Packages/com.unity.visualscripting@1.6/manual/vs-control.html) and [Unreal Blueprint](https://dev.epicgames.com/documentation/en-us/unreal-engine/nodes-in-unreal-engine) manages control and data flow between their nodes.
> feat: implement control flow edge semantics and loop step

- unicon_backend/evaluator/tasks/programming/runner.py
- unicon_backend/evaluator/tasks/programming/task.py
- adds files in graph to package to send to runner
- sends multiple testcases in 1 request
> refactor: send packages to dumb runner

- unicon_backend/app.py
- unicon_backend/lib/amqp.py
- unicon_backend/workers.py
> fix: task publisher transport EOF error

- unicon_backend/evaluator/tasks/programming/security.py
- unicon_backend/evaluator/tasks/programming/steps.py
- unicon_backend/evaluator/tasks/programming/task.py
to improve security
i know it will stop inplace editing because when i made utils use it at first it while Trued to TLE because the state was stuck at the initial board
> feat: untrusted code isolation via `multiprocessing`

- examples/README.md
- examples/addition/definitions/allow_error.json
- examples/addition/definitions/simple.json
- examples/addition/definitions/with_evaluation.json
- examples/addition/submissions/ace.json
- examples/addition/submissions/correct.json
- examples/addition/submissions/error.json
- examples/addition/submissions/variable_overwrite.json
- examples/addition/submissions/wrong.json
- unicon_backend/evaluator/tasks/programming/security.py
- unicon_backend/evaluator/tasks/programming/steps.py
This PR attempts to do "Go" like error handling.
- behavior: output `{"file_name": ..., "function_name": ..., "error": ... }` to stdout
- should it be in stdout? (still distinguishable from OK by return code)
To test this PR, try the addition definitions (`allow_error.json`, `simple.json`) with `error.json` as submission
fixes #45
> feat: `PyRunFunction` error handling

- unicon_backend/evaluator/tasks/programming/task.py
- unicon_backend/runner.py
Accompanying PR: https://github.com/uniconhq/unicon-runner/pull/14
_The changes in this PR are just schema changes to support the features introduced in the `unicon-runner` PR (above)._
> feat: support for `slurm` compute context

- unicon_backend/routers/problem.py
- unicon_backend/workers/consumer.py
- stops overwriting of RTE/TLE to WA
- add the routes i forgot to commit
> fix: don't overwrite error status

- unicon_backend/models/problem.py
- unicon_backend/routers/problem.py
complements https://github.com/uniconhq/unicon-frontend/pull/13
> feat: new endpoint to get results of task attempts 

- .github/workflows/deploy.yaml
honestly idk how to test if this works without merging it
> ci: deploy to ghcr

- examples/addition/definitions/allow_error.json
- examples/addition/definitions/comparison.json
- examples/addition/definitions/simple.json
- examples/breakthrough/definition.json
- examples/problem_set/definition.json
- unicon_backend/evaluator/tasks/programming/artifact.py
- unicon_backend/evaluator/tasks/programming/steps.py
This PR adds a custom socket data model for `PyRunFunctionStep` to allow us to identify args, kwargs and module files in a deterministic manner (guaranteed by pydantic validation)
Additionally, all args and kwargs can be pre-filled without the need for an in-link from another node. This is to allow for smaller graphs, and also to cater to user preferences. _In some cases, this could also help with a stronger enforcement of constant values._ An example usage can be found in the "Problem Set" definition file under https://github.com/uniconhq/unicon-backend/pull/74/commits/fe64b17cce016ef73211f396af23d3eff54a8711.
> feat: custom socket validation for `PyRunFunction`

- unicon_backend/routers/auth.py
attempt 1 at fixing 
https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure
> fix: set cookie SameSite=None

- unicon_backend/routers/problem.py
- unicon_backend/runner.py
versions acquired by eyeballing `uv python list` on xlog0
> feat: add python versions endpoint

- unicon_backend/cli.py
calling schemas_list with no schema actually errors (tested with v1.3.0) instead of returning an empty list. wrap with try-catch
> fix: permify initial init

- unicon_backend/routers/auth.py
- add the same settings used in login cookie to fix logout
- hopefully fixes https://github.com/uniconhq/frontend/issues/52
> fix: secure logout cookie

- unicon_backend/lib/permissions.py
- unicon_backend/routers/organisation.py
- unicon_backend/schemas/organisation.py
- unicon_backend/unicon.perm
- users in a project of the organisation can now view the organisation (but only projects they are in). this is needed for the frontend breadcrumb fix: https://github.com/uniconhq/frontend/pull/87
> feat: organisation permission fix

- unicon_backend/evaluator/tasks/programming/base.py
- unicon_backend/evaluator/tasks/programming/steps.py
- censoring of input sockets' value
https://github.com/uniconhq/frontend/pull/93
> feat: private inputs

- .github/workflows/deploy.yaml
- https://github.com/uniconhq/infra/commit/16864a129c4d7df2bc6145db28ab97e303b677df
> ci: `watchtower` auto base image upgrade on deploy

- unicon_backend/evaluator/tasks/programming/templates/mpi_sandbox.py
the problem:
https://unicon.run/projects/1/problems/1
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/stuproj/unicon/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/multiprocessing/spawn.py", line 122, in spawn_main
exitcode = _main(fd, parent_sentinel)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/stuproj/unicon/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/multiprocessing/spawn.py", line 131, in _main
prepare(preparation_data)
File "/home/stuproj/unicon/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/multiprocessing/spawn.py", line 246, in prepare
_fixup_main_from_path(data['init_main_from_path'])
File "/home/stuproj/unicon/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python …
```
> fix: mp parts need __name__ == "__main__"

- unicon_backend/evaluator/tasks/programming/harness.py
- unicon_backend/evaluator/tasks/programming/steps.py
- unicon_backend/evaluator/tasks/programming/templates/mpi_sandbox.py
- Ensure that there's only 1 `__name__ == '__main__'` block
- Reduce duplicated logic in harness
> refactor: restructure `mpi_sandbox` harness

- unicon_backend/evaluator/problem.py
- unicon_backend/evaluator/tasks/base.py
- unicon_backend/evaluator/tasks/programming/steps.py
- unicon_backend/lib/common.py
- unicon_backend/models/problem.py
- unicon_backend/runner.py
Closes #117 
The following is a comparison between validation errors before and after the fix for a node that is missing a mandatory socket:
Before:
```
ValidationError: 15 validation errors for Problem
tasks.0.PROGRAMMING_TASK.max_attempts
Field required [type=missing, input_value={'id': 0, 'type': 'PROGRA...t_id': '__MODULE__'}]}]}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.10/v/missing
tasks.0.PROGRAMMING_TASK.testcases.0.nodes.2.function-after[check_required_inputs_and_outputs(), 
function-wrap[__convert_to_real_type__()]].function_identifier
Extra inputs are not permitted [type=extra_forbidden, input_value='add', input_type=str]
For further information visit https://errors.pydantic.dev/2.10/v/extra_forbidden …
```
> fix: overly verbose validation errors for `Step` nodes

- unicon_backend/schemas/organisation.py
- remove requirement for unnecessary permissions
closes https://github.com/uniconhq/unicon/issues/8
> fix: organisation user page

- unicon_backend/evaluator/tasks/programming/artifact.py
- unicon_backend/evaluator/tasks/programming/base.py
- unicon_backend/lib/file.py
- unicon_backend/models/problem.py
- unicon_backend/routers/problem.py
- unicon_backend/runner.py
frontend PR: https://github.com/uniconhq/frontend/pull/127
closes #132
> feat: user file size limit

- unicon_backend/routers/project.py
- unicon_backend/unicon.perm
closes https://github.com/uniconhq/unicon/issues/13
> feat(project): edit and delete

- unicon_backend/routers/project.py
- unicon_backend/schemas/organisation.py
related to https://github.com/uniconhq/unicon/issues/11
> feat: project user management

- unicon_backend/routers/problem.py
merge ~~after #143~~ and after user testing is done (16/04/25 23:59)
> refactor: create submission on marked attempt
